resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/honnuanand/wings-boot.git
    branch: master

- name: jar-store
  type: artifactory
  source:
    endpoint: http://192.168.100.1:8081/artifactory
    repository: "/jar-files/wings-boot"
    regex: "wings-boot(?.*).jar"
    username: admin
    password: password
    skip_ssl_verification: true

jobs:
- name: package
  plan:
  - get: source-code
    trigger: true
  - task: package
    privileged: true
    file: source-code/ci/tasks/package.yml
  - put: jar-store
    params:
      file: app-jar/wings-boot*.jar


- name: just-list
  plan:
  - get: source-code
    trigger: true
  - task: list-repo-content
    config:
      platform: linux
      inputs:
      - name: source-code
      image_resource:
        type: docker-image
        source: { repository: ubuntu }
      run:
        path: sh
        args:
        - -exc
        - |
          ls -R ./source-code
