resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/honnuanand/wings-boot.git
    branch: alb-demo

- name: Pivotal-Cloud-Foundry
  type: cf
  source:
    api: ((cf-api-endpoint))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: ((cf-space))
    skip_cert_check: ((cf-skip-cert-check))
  
- name: wings-boot-repo
  type: artifactory
  source:
    endpoint: ((artifactory-uri))
    repository: ((artifactory-repository))
    regex: ((artifactory-regex))
    username: ((artifactory-user))
    password: ((artifactory-password))
    skip_ssl_verification: ((artifactory-skip-cert-check))

jobs:
- name: build-binary
  plan:
  - get: source-code
    trigger: true
  - task: package
    privileged: true
    file: source-code/ci/tasks/package.yml
  - put: wings-boot-repo
    params:
      file: app-jar/wings-boot*.jar

- name: deploy-to-pcf
  plan:
  - get: source-code
  - get: wings-boot-repo
    trigger: true
    passed: ['build-binary']

  - put: Pivotal-Cloud-Foundry
    params:
      path: ./wings-boot-repo/wings-boot*.jar
      manifest: source-code/manifest.yml
