resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource


resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/honnuanand/wings-boot.git
    branch: cfci



- name: deployment
  type: cf
  source:
    api: https://api.sys.cf.az.clue2solve.com
    username: arao
    password: p@ssw0rd!
    organization: workshop
    space: demo
    skip_cert_check: true


jobs:
- name: package
  plan:
  - get: source-code
    trigger: true
  - task: package
    privileged: true
    file: source-code/ci/tasks/package.yml
  - put: deployment
    params:
      path: app-jar/wings-boot*.jar
      manifest: app-jar/manifest.yml



- name: just-list
  plan:
  - get: source-code
    trigger: true
  - task: list-repo-content
    config:
      platform: linux
      inputs:
      - name: source-code
      image_resource:
        type: docker-image
        source: { repository: ubuntu }
      run:
        path: sh
        args:
        - -exc
        - |
          ls -R ./source-code
